#!/usr/bin/python                                                                                                                                                                                                                        
                                                                                                                                                                                                                                         
import sys                                                                                                                                                                                                                               
import datetime                                                                                                                                                                                                                          
import os                                                                                                                                                                                                                                
import send_email_report as ser                                                                                                                                                                                                          
from time import sleep                                                                                                                                                                                                                   
                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                         
source_file = sys.argv[1]                                                                                                                                                                                                                
                                                                                                                                                                                                                                         
f = open(source_file)                                                                                                                                                                                                                    
write = open(source_file+".csv",'w')                                                                                                                                                                                                     
buffer = ""                                                                                                                                                                                                                              
#write.write("Symbol,shares,price")                                                                                                                                                                                                      
for row in f:                                                                                                                                                                                                                            
        parsed = row.split(",")                                                                                                                                                                                                          
        price = parsed[0]                                                                                                                                                                                                                
        price = price[price.index("[")+1:].lstrip().rstrip()                                                                                                                                                                             
        symbol = parsed[3].lstrip().rstrip()                                                                                                                                                                                             
        symbol = symbol.replace("'","")                                                                                                                                                                                                  
        action = parsed[1].lstrip().rstrip()                                                                                                                                                                                             
        action = action.replace("'","")                                                                                                                                                                                                  
        shares = parsed[2].lstrip().rstrip()                                                                                                                                                                                             
                                                                                                                                                                                                                                         
        if action == "SLD":                                                                                                                                                                                                              
                action = "Sell Short"
        else:
                action = "Buy"
        buffer = buffer+"\""+symbol+"\","+ price+",\""+action+"\","+ str(shares)+"\n"                                                                                                                                                                          
                                                                                                                                                                                                                                         
buffer = "\"Symbol\",\"Purchase price per share\",\"Transaction type\",\"Shares\"\n"+buffer                                                                                                                                                                       
print str(buffer)                                                                                                                                                                                                                        
write.write(buffer)                                                                                                                                                                                                                      
write.close()    

